version: 2.1

jobs:
  lint:
    docker:
      - image: node:18
    resource_class: large
    parallelism: 10

    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-9 --activate
            pnpm config set store-dir .pnpm-store
      - run:
          name: Install Dev Dependencies
          command: |
            pnpm install --dev
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store
      - run:
          name: Check ESLint
          command: |
            git diff --name-only --diff-filter=ACMRUXB origin/main | grep -E '\.(js|ts|tsx)$' | xargs -r pnpm eslint
      - run:
          name: Check Prettier
          command: |
            git diff --name-only --diff-filter=ACMRUXB origin/main | xargs -r pnpm prettier --check
